package pl.execon.tmo.main.java.locators;

public class WithDeviceNoLimitGridLocators {
    public static final String FIRST_SECTION_OFFER_HEADER_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-offer-name > div > span:nth-child(1)";
    public static final String FIRST_SECTION_OFFER_HEADER_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-offer-name > div > span.offer-name__name.offer-name__name--sub";
    public static final String FIRST_SECTION_BILL_PAID_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-bill-paid > div > div > span";
    public static final String FIRST_SECTION_BILL_PAID_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-bill-paid > div > span";
    public static final String FIRST_SECTION_BILL_PAID_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-bill-paid > div > div > img";
    public static final String FIRST_SECTION_SMS_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-sms > div > div > span";
    public static final String FIRST_SECTION_SMS_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-sms > div > span";
    public static final String FIRST_SECTION_SMS_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-sms > div > div > img";
    public static final String FIRST_SECTION_INTERNET_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-internet > div > div:nth-child(1) > span";
    public static final String FIRST_SECTION_INTERNET_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-internet > div > div.price-wrapper > p";
    public static final String FIRST_SECTION_INTERNET_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-internet > div > div:nth-child(1) > img";
    public static final String FIRST_SECTION_CHOOSE_MONTH_PAYMENT_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-next-button > div > div:nth-child(1) > p.h3";
    public static final String FIRST_SECTION_CHOOSE_MONTH_PAYMENT_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-next-button > div > div:nth-child(1) > p.h4";
    public static final String FIRST_SECTION_PRICE_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-next-button > div > div.price-wrapper > div > div > p";
    public static final String FIRST_SECTION_LEFT_PRICE_ADJUSTMENT_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-next-button > div > div.price-wrapper > div > p.btn-left.net";
    public static final String FIRST_SECTION_RIGHT_PRICE_ADJUSTMENT_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-next-button > div > div.price-wrapper > div > p.btn-right.net";
    public static final String FIRST_SECTION_PICK_PHONE_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-next-button > div > a";
    public static final String FIRST_SECTION_SUBSCRIPTION_LENGTH_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-next-button > div > p";
    public static final String FIRST_SECTION_BONUS_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-bonuses > div > span";
    public static final String FIRST_SECTION_FREE_SHIPMENT_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-bonuses > div > div > div:nth-child(1) > span";
    public static final String FIRST_SECTION_DISCOUNT_FOR_ONLINE_ORDER_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(1) > div > app-bonuses > div > div > div:nth-child(2) > span";

    public static final String SECOND_SECTION_OFFER_HEADER_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-offer-name > div > span:nth-child(1)";
    public static final String SECOND_SECTION_OFFER_HEADER_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-offer-name > div > span.offer-name__name.offer-name__name--sub";
    public static final String SECOND_SECTION_BILL_PAID_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-bill-paid > div > div > span";
    public static final String SECOND_SECTION_BILL_PAID_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-bill-paid > div > span";
    public static final String SECOND_SECTION_BILL_PAID_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-bill-paid > div > div > img";
    public static final String SECOND_SECTION_SMS_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-sms > div > div > span";
    public static final String SECOND_SECTION_SMS_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-sms > div > span";
    public static final String SECOND_SECTION_SMS_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-sms > div > div > img";
    public static final String SECOND_SECTION_INTERNET_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-internet > div > div:nth-child(1) > span";
    public static final String SECOND_SECTION_INTERNET_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-internet > div > div.price-wrapper > p";
    public static final String SECOND_SECTION_INTERNET_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-internet > div > div:nth-child(1) > img";
    public static final String SECOND_SECTION_CHOOSE_MONTH_PAYMENT_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-next-button > div > div:nth-child(1) > p.h3";
    public static final String SECOND_SECTION_CHOOSE_MONTH_PAYMENT_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-next-button > div > div:nth-child(1) > p.h4";
    public static final String SECOND_SECTION_PRICE_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-next-button > div > div.price-wrapper > div > div > p";
    public static final String SECOND_SECTION_LEFT_PRICE_ADJUSTMENT_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-next-button > div > div.price-wrapper > div > p.btn-left.net";
    public static final String SECOND_SECTION_RIGHT_PRICE_ADJUSTMENT_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-next-button > div > div.price-wrapper > div > p.btn-right.net";
    public static final String SECOND_SECTION_PICK_PHONE_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-next-button > div > a";
    public static final String SECOND_SECTION_SUBSCRIPTION_LENGTH_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-next-button > div > p";
    public static final String SECOND_SECTION_BONUS_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-bonuses > div > span";
    public static final String SECOND_SECTION_FREE_SHIPMENT_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-bonuses > div > div > div:nth-child(1) > span";
    public static final String SECOND_SECTION_DISCOUNT_FOR_ONLINE_ORDER_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(2) > div > app-bonuses > div > div > div:nth-child(2) > span";

    public static final String THIRD_SECTION_OFFER_HEADER_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-offer-name > div > span:nth-child(1)";
    public static final String THIRD_SECTION_OFFER_HEADER_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-offer-name > div > span.offer-name__name.offer-name__name--sub";
    public static final String THIRD_SECTION_BILL_PAID_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-bill-paid > div > div > span";
    public static final String THIRD_SECTION_BILL_PAID_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-bill-paid > div > span";
    public static final String THIRD_SECTION_BILL_PAID_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-bill-paid > div > div > img";
    public static final String THIRD_SECTION_SMS_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-sms > div > div > span";
    public static final String THIRD_SECTION_SMS_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-sms > div > span";
    public static final String THIRD_SECTION_SMS_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-sms > div > div > img";
    public static final String THIRD_SECTION_INTERNET_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-internet > div > div:nth-child(1) > span";
    public static final String THIRD_SECTION_INTERNET_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-internet > div > div.price-wrapper > p";
    public static final String THIRD_SECTION_INTERNET_TOOLTIP_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-internet > div > div:nth-child(1) > img";
    public static final String THIRD_SECTION_CHOOSE_MONTH_PAYMENT_PT1_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-next-button > div > div:nth-child(1) > p.h3";
    public static final String THIRD_SECTION_CHOOSE_MONTH_PAYMENT_PT2_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-next-button > div > div:nth-child(1) > p.h4";
    public static final String THIRD_SECTION_CONSTANT_PRICE_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-next-button > div > div.price-wrapper > div > div:nth-child(2) > p.smaller-h1.pink";
    public static final String THIRD_SECTION_DYNAMIC_PRICE_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-next-button > div > div.price-wrapper > div > div:nth-child(3) > p.smaller-h1";
    public static final String THIRD_SECTION_LEFT_PRICE_ADJUSTMENT_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-next-button > div > div.price-wrapper > div > p.btn-left.net";
    public static final String THIRD_SECTION_RIGHT_PRICE_ADJUSTMENT_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-next-button > div > div.price-wrapper > div > p.btn-right.net";
    public static final String THIRD_SECTION_PICK_PHONE_BUTTON_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-next-button > div > a";
    public static final String THIRD_SECTION_SUBSCRIPTION_LENGTH_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-next-button > div > p";
    public static final String THIRD_SECTION_BONUS_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-bonuses > div > span";
    public static final String THIRD_SECTION_FREE_SHIPMENT_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-bonuses > div > div > div:nth-child(1) > span";
    public static final String THIRD_SECTION_DISCOUNT_FOR_ONLINE_ORDER_INFORMATION_CSS = "#plans-list > app-root > offer-boxes > ngx-slick > div > div > offer-box:nth-child(3) > div > app-bonuses > div > div > div:nth-child(2) > span";

}
