package pl.execon.tmo.main.java.webelements;

import org.openqa.selenium.WebElement;
import pl.execon.tmo.main.java.builders.PageInterface;

public class BaseGridClass implements PageInterface {
    private WebElement firstSectionOfferHeaderPT1;
    private WebElement firstSectionBillPaidPT1;
    private WebElement firstSectionBillPaidPT2;
    private WebElement firstSectionBillPaidTooltip;
    private WebElement firstSectionSmsPT1;
    private WebElement firstSectionSmsPT2;
    private WebElement firstSectionSmsTooltip;
    private WebElement firstSectionInternetPT1;
    private WebElement firstSectionInternetPT2;
    private WebElement firstSectionInternetTooltip;
    private WebElement firstSectionChooseMonthPaymentPT1;
    private WebElement firstSectionChooseMonthPaymentPT2;
    private WebElement firstSectionPrice;
    private WebElement firstSectionLeftPriceAdjustmentButton;
    private WebElement firstSectionRightPriceAdjustmentButton;
    private WebElement firstSectionPickPhoneButton;
    private WebElement firstSectionSubscriptionLengthInformation;
    private WebElement firstSectionBonusInformation;
    private WebElement firstSectionFreeShipmentInformation;
    private WebElement firstSectionDiscountForOnlineOrderInformation;

    //Second section
    private WebElement secondSectionOfferHeaderPT1;
    private WebElement secondSectionBillPaidPT1;
    private WebElement secondSectionBillPaidPT2;
    private WebElement secondSectionBillPaidTooltip;
    private WebElement secondSectionSmsPT1;
    private WebElement secondSectionSmsPT2;
    private WebElement secondSectionSmsTooltip;
    private WebElement secondSectionInternetPT1;
    private WebElement secondSectionInternetPT2;
    private WebElement secondSectionInternetTooltip;
    private WebElement secondSectionChooseMonthPaymentPT1;
    private WebElement secondSectionChooseMonthPaymentPT2;
    private WebElement secondSectionPrice;
    private WebElement secondSectionLeftPriceAdjustmentButton;
    private WebElement secondSectionRightPriceAdjustmentButton;
    private WebElement secondSectionPickPhoneButton;
    private WebElement secondSectionSubscriptionLengthInformation;
    private WebElement secondSectionBonusInformation;
    private WebElement secondSectionFreeShipmentInformation;
    private WebElement secondSectionDiscountForOnlineOrderInformation;

    //Third section
    private WebElement thirdSectionOfferHeaderPT1;
    private WebElement thirdSectionBillPaidPT1;
    private WebElement thirdSectionBillPaidPT2;
    private WebElement thirdSectionBillPaidTooltip;
    private WebElement thirdSectionSmsPT1;
    private WebElement thirdSectionSmsPT2;
    private WebElement thirdSectionSmsTooltip;
    private WebElement thirdSectionInternetPT1;
    private WebElement thirdSectionInternetPT2;
    private WebElement thirdSectionInternetTooltip;
    private WebElement thirdSectionChooseMonthPaymentPT1;
    private WebElement thirdSectionChooseMonthPaymentPT2;
    private WebElement thirdSectionConstantPrice;
    private WebElement thirdSectionDynamicPrice;
    private WebElement thirdSectionLeftPriceAdjustmentButton;
    private WebElement thirdSectionRightPriceAdjustmentButton;
    private WebElement thirdSectionPickPhoneButton;
    private WebElement thirdSectionSubscriptionLengthInformation;
    private WebElement thirdSectionBonusInformation;
    private WebElement thirdSectionFreeShipmentInformation;
    private WebElement thirdSectionDiscountForOnlineOrderInformation;

    public BaseGridClass(WebElement firstSectionOfferHeaderPT1, WebElement firstSectionBillPaidPT1, WebElement firstSectionBillPaidPT2, WebElement firstSectionBillPaidTooltip, WebElement firstSectionSmsPT1, WebElement firstSectionSmsPT2, WebElement firstSectionSmsTooltip, WebElement firstSectionInternetPT1, WebElement firstSectionInternetPT2, WebElement firstSectionInternetTooltip, WebElement firstSectionChooseMonthPaymentPT1, WebElement firstSectionChooseMonthPaymentPT2, WebElement firstSectionPrice, WebElement firstSectionLeftPriceAdjustmentButton, WebElement firstSectionRightPriceAdjustmentButton, WebElement firstSectionPickPhoneButton, WebElement firstSectionSubscriptionLengthInformation, WebElement firstSectionBonusInformation, WebElement firstSectionFreeShipmentInformation, WebElement firstSectionDiscountForOnlineOrderInformation, WebElement secondSectionOfferHeaderPT1, WebElement secondSectionBillPaidPT1, WebElement secondSectionBillPaidPT2, WebElement secondSectionBillPaidTooltip, WebElement secondSectionSmsPT1, WebElement secondSectionSmsPT2, WebElement secondSectionSmsTooltip, WebElement secondSectionInternetPT1, WebElement secondSectionInternetPT2, WebElement secondSectionInternetTooltip, WebElement secondSectionChooseMonthPaymentPT1, WebElement secondSectionChooseMonthPaymentPT2, WebElement secondSectionPrice, WebElement secondSectionLeftPriceAdjustmentButton, WebElement secondSectionRightPriceAdjustmentButton, WebElement secondSectionPickPhoneButton, WebElement secondSectionSubscriptionLengthInformation, WebElement secondSectionBonusInformation, WebElement secondSectionFreeShipmentInformation, WebElement secondSectionDiscountForOnlineOrderInformation, WebElement thirdSectionOfferHeaderPT1, WebElement thirdSectionBillPaidPT1, WebElement thirdSectionBillPaidPT2, WebElement thirdSectionBillPaidTooltip, WebElement thirdSectionSmsPT1, WebElement thirdSectionSmsPT2, WebElement thirdSectionSmsTooltip, WebElement thirdSectionInternetPT1, WebElement thirdSectionInternetPT2, WebElement thirdSectionInternetTooltip, WebElement thirdSectionChooseMonthPaymentPT1, WebElement thirdSectionChooseMonthPaymentPT2, WebElement thirdSectionConstantPrice, WebElement thirdSectionDynamicPrice, WebElement thirdSectionLeftPriceAdjustmentButton, WebElement thirdSectionRightPriceAdjustmentButton, WebElement thirdSectionPickPhoneButton, WebElement thirdSectionSubscriptionLengthInformation, WebElement thirdSectionBonusInformation, WebElement thirdSectionFreeShipmentInformation, WebElement thirdSectionDiscountForOnlineOrderInformation) {
        this.firstSectionBillPaidPT1 = firstSectionBillPaidPT1;
        this.firstSectionBillPaidPT2 = firstSectionBillPaidPT2;
        this.firstSectionBillPaidTooltip = firstSectionBillPaidTooltip;
        this.firstSectionSmsPT1 = firstSectionSmsPT1;
        this.firstSectionSmsPT2 = firstSectionSmsPT2;
        this.firstSectionSmsTooltip = firstSectionSmsTooltip;
        this.firstSectionInternetPT1 = firstSectionInternetPT1;
        this.firstSectionInternetPT2 = firstSectionInternetPT2;
        this.firstSectionInternetTooltip = firstSectionInternetTooltip;
        this.firstSectionChooseMonthPaymentPT1 = firstSectionChooseMonthPaymentPT1;
        this.firstSectionChooseMonthPaymentPT2 = firstSectionChooseMonthPaymentPT2;
        this.firstSectionPrice = firstSectionPrice;
        this.firstSectionPickPhoneButton = firstSectionPickPhoneButton;
        this.firstSectionSubscriptionLengthInformation = firstSectionSubscriptionLengthInformation;
        this.firstSectionBonusInformation = firstSectionBonusInformation;
        this.firstSectionFreeShipmentInformation = firstSectionFreeShipmentInformation;
        this.firstSectionDiscountForOnlineOrderInformation = firstSectionDiscountForOnlineOrderInformation;
        this.secondSectionOfferHeaderPT1 = secondSectionOfferHeaderPT1;
        this.secondSectionBillPaidPT1 = secondSectionBillPaidPT1;
        this.secondSectionBillPaidPT2 = secondSectionBillPaidPT2;
        this.secondSectionBillPaidTooltip = secondSectionBillPaidTooltip;
        this.secondSectionSmsPT1 = secondSectionSmsPT1;
        this.secondSectionSmsPT2 = secondSectionSmsPT2;
        this.secondSectionSmsTooltip = secondSectionSmsTooltip;
        this.secondSectionInternetPT1 = secondSectionInternetPT1;
        this.secondSectionInternetPT2 = secondSectionInternetPT2;
        this.secondSectionInternetTooltip = secondSectionInternetTooltip;
        this.secondSectionChooseMonthPaymentPT1 = secondSectionChooseMonthPaymentPT1;
        this.secondSectionChooseMonthPaymentPT2 = secondSectionChooseMonthPaymentPT2;
        this.secondSectionPrice = secondSectionPrice;
        this.secondSectionPickPhoneButton = secondSectionPickPhoneButton;
        this.secondSectionSubscriptionLengthInformation = secondSectionSubscriptionLengthInformation;
        this.secondSectionBonusInformation = secondSectionBonusInformation;
        this.secondSectionFreeShipmentInformation = secondSectionFreeShipmentInformation;
        this.secondSectionDiscountForOnlineOrderInformation = secondSectionDiscountForOnlineOrderInformation;
        this.thirdSectionOfferHeaderPT1 = thirdSectionOfferHeaderPT1;
        this.thirdSectionBillPaidPT1 = thirdSectionBillPaidPT1;
        this.thirdSectionBillPaidPT2 = thirdSectionBillPaidPT2;
        this.thirdSectionBillPaidTooltip = thirdSectionBillPaidTooltip;
        this.thirdSectionSmsPT1 = thirdSectionSmsPT1;
        this.thirdSectionSmsPT2 = thirdSectionSmsPT2;
        this.thirdSectionSmsTooltip = thirdSectionSmsTooltip;
        this.thirdSectionInternetPT1 = thirdSectionInternetPT1;
        this.thirdSectionInternetPT2 = thirdSectionInternetPT2;
        this.thirdSectionInternetTooltip = thirdSectionInternetTooltip;
        this.thirdSectionChooseMonthPaymentPT1 = thirdSectionChooseMonthPaymentPT1;
        this.thirdSectionChooseMonthPaymentPT2 = thirdSectionChooseMonthPaymentPT2;
        this.thirdSectionConstantPrice = thirdSectionConstantPrice;
        this.thirdSectionDynamicPrice = thirdSectionDynamicPrice;
        this.thirdSectionPickPhoneButton = thirdSectionPickPhoneButton;
        this.thirdSectionSubscriptionLengthInformation = thirdSectionSubscriptionLengthInformation;
        this.thirdSectionBonusInformation = thirdSectionBonusInformation;
        this.thirdSectionFreeShipmentInformation = thirdSectionFreeShipmentInformation;
        this.thirdSectionDiscountForOnlineOrderInformation = thirdSectionDiscountForOnlineOrderInformation;
    }
}
